name: mix ${{inputs.task}}
description: "Runs a mix task"
inputs:
  mix-env:
    description: "The Mix environment to compile within"
    required: true
  working-directory:
    description: "Change the working directory that the commands are run within"
    required: false
    default: "${{ github.workspace }}"
  task:
    description: "The task to run"
    required: true
runs:
  using: "composite"
  steps:
    - run: mix ${{inputs.task}}
      shell: bash
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      working-directory: "${{ inputs.working-directory }}"
