name: Elixir Library

on:
  push:

jobs:
  deps:
    name: mix deps.get
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get

  auditor:
    name: mix hex.audit
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get
      - run: mix hex.audit

  build-test:
    name: MIX_ENV=test mix.compile
    runs-on: ubuntu-latest
    needs: deps
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get
      - uses: team-alembic/staple-actions/actions/mix-compile
        with:
          mix-env: test

  formatter:
    name: mix format --check-formatted
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get
      - uses: team-alembic/staple-actions/actions/mix-compile
        with:
          mix-env: ${{ env.MIX_ENV }}
      - run: mix format --check-formatted

  credo:
    name: mix credo --strict
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get
      - uses: team-alembic/staple-actions/actions/mix-compile
        with:
          mix-env: ${{ env.MIX_ENV }}
      - run: mix credo --strict

  doctor:
    name: mix doctor --full --raise
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get
      - uses: team-alembic/staple-actions/actions/mix-compile
        with:
          mix-env: ${{ env.MIX_ENV }}
      - run: mix doctor --full --raise

  test:
    name: mix test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get
      - uses: team-alembic/staple-actions/actions/mix-compile
        with:
          mix-env: ${{ env.MIX_ENV }}
      - run: mix test

  dialyzer:
    name: mix dialyzer
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get
      - uses: team-alembic/staple-actions/actions/mix-compile
        with:
          mix-env: ${{ env.MIX_ENV }}
      - uses: team-alembic/staple-actions/actions/mix-dialyzer-plt
        with:
          mix-env: ${{ env.MIX_ENV }}
      - run: mix dialyzer --format github

  build-dev:
    name: MIX_ENV=dev mix.compile
    runs-on: ubuntu-latest
    needs:
      - credo
      - doctor
      - formatter
      - auditor
      - test
      - dialyzer
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get
      - uses: team-alembic/staple-actions/actions/mix-compile
        with:
          mix-env: dev

  build-docs:
    name: mix docs
    runs-on: ubuntu-latest
    needs: build-dev
    env:
      MIX_ENV: dev
    steps:
      - uses: actions/checkout@v3
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get
      - uses: team-alembic/staple-actions/actions/mix-compile
        with:
          mix-env: ${{ env.MIX_ENV }}
      - run: mix docs
      - uses: actions/upload-pages-artifact@v1
        with:
          path: doc/

  deploy-docs:
    name: Deploy docs to GitHub pages.
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v1

  git-ops:
    name: mix git-ops.release
    runs-on: ubuntu-latest
    needs: build-dev
    env:
      MIX_ENV: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: team-alembic/staple-actions/actions/install-elixir
      - uses: team-alembic/staple-actions/actions/mix-deps-get
      - uses: team-alembic/staple-actions/actions/mix-compile
        with:
          mix-env: ${{ env.MIX_ENV }}
      - uses: team-alembic/staple-actions/actions/git-ops
