name: mix git_ops.check_message
description: "Runs `mix git_ops.check_message`"
inputs:
  git-token:
    required: false
    default: ${{ github.token }}
    description: "A Github access token for checking out git-based dependencies."
  mix-env:
    description: "The Mix environment to compile within"
    required: true
  working-directory:
    description: "Change the working directory that the commands are run within"
    required: false
    default: "${{ github.workspace }}"
  use-cache:
    description: "Use caches?"
    required: false
    default: "true"
  cache-prefix:
    description: "Optional prefix for the cache key"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: team-alembic/staple-actions/actions/mix-compile@main
      with:
        git-token: ${{ inputs.git-token }}
        working-directory: ${{ inputs.working-directory }}
        use-cache: ${{ inputs.use-cache }}
        cache-prefix: ${{ inputs.cache-prefix }}
        mix-env: ${{ inputs.mix-env }}
    - run: git log -1 --format=%s ${{ github.event.pull_request.head.sha }}> .last_commit_message
      shell: bash
      working-directory: "${{ inputs.working-directory }}"
    - run: mix git_ops.check_message .last_commit_message
      shell: bash
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      working-directory: "${{ inputs.working-directory }}"
