name: mix compile
description: "Run `mix compile` with a build cache"
inputs:
  mix-env:
    description: "The Mix environment to compile within"
    required: true
  working-directory:
    description: "Change the working directory that the commands are run within"
    required: false
    default: "${{ github.workspace }}"
  use-cache:
    description: "Whether to cache the build results"
    required: false
    default: "true"
  cache-prefix:
    description: "Optional prefix for the cache key"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Retrieve Build Cache
      uses: actions/cache@v1
      id: build-cache
      with:
        path: "${{ inputs.working-directory }}/_build/${{ inputs.mix-env }}"
        key: ${{ inputs.cache-prefix}}-build-${{ inputs.mix-env }}-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles(format('{0}{1}', inputs.working-directory, '/.tool-versions')) }}-${{ hashFiles(format('{0}{1}', inputs.working-directory, '/mix.lock')) }}
      if: ${{ inputs.use-cache == 'true' }}
    - run: mix compile
      shell: bash
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        HEX_HOME: ${{ runner.temp }}/.hex
        MIX_HOME: ${{ runner.temp }}/.mix
      working-directory: "${{ inputs.working-directory }}"
